services:
  server:
    restart: unless-stopped
    volumes:
      - ./steamapps:/wine/steamapps/
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SBOX_SERVER_ARGUMENTS=+game facepunch.walker
    image: giodotblue/sbox-server:debian-wine-v2